server:
  port: 8081
management:
  server:
    port: 9002
    address: 127.0.0.1
spring:
  application:
    name: account-msf
  data:
    mongodb:
      url: mongodb://localhost:27017
      database: account_bd
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true
    hostname: host.docker.internal
    leaseRenewalIntervalInSeconds: 30
    leaseExpirationDurationInSeconds: 90
