server:
  port: 8086
management:
  server:
    port: 9007
  endpoints:
    web:
      basePath: /actuator/info
spring:
  application:
    name: bootcoin-msf
  data:
    mongodb:
      url: mongodb://localhost:27017
      database: bootcoin_bd
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true
    hostname: host.docker.internal
    leaseRenewalIntervalInSeconds: 30
    leaseExpirationDurationInSeconds: 90
