server:
  port: 8082
management:
  server:
    port: 9003
  endpoints:
    web:
      basePath: /actuator/info
spring:
  application:
    name: credit-msf
  data:
    mongodb:
      url: mongodb://localhost:27017
      database: credit_bd
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true
    hostname: host.docker.internal
    leaseRenewalIntervalInSeconds: 30
    leaseExpirationDurationInSeconds: 90
