server:
  port: 8084
management:
  server:
    port: 9005
    address: 127.0.0.1
spring:
  application:
    name: debit-msf
  data:
    mongodb:
      url: mongodb://localhost:27017
      database: debit_bd
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    leaseRenewalIntervalInSeconds: 30
    leaseExpirationDurationInSeconds: 90
