server:
  port: 8090
spring:
  application:
    name: gateway-msf
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    leaseRenewalIntervalInSeconds: 30
    leaseExpirationDurationInSeconds: 90