server:
  port: 8090
spring:
  application:
    name: gateway-msf
  cloud: 
    gateway:
      routes:
        - id: client-msf
          uri: lb://client-msf
          predicates:
            - Path=/api/client/**
          filters:
            - StripPrefix=0
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    leaseRenewalIntervalInSeconds: 30
    leaseExpirationDurationInSeconds: 90
